# Custom Language File for Launcher Customizer

[ejs.app]
title = "가내수공업_외주용"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/handmade_out"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/handmade_out"
supportLink = "https://github.com/CustomLauncherLab/handmade_out/issues"

[ejs.welcome]
welcomeHeader = "가내수공업_외주용"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."